### ISSUE TITLE
two rules don't exist in `JavaScript`

### ISSUE THREAD

**Issue by RedCMD** [ruschaaf/extended-embedded-languages#10]
![image](https://github.com/ruschaaf/extended-embedded-languages/assets/33529441/ab9f53b1-d996-4c20-8552-d5c9a65655dd)

https://github.com/ruschaaf/extended-embedded-languages/blob/c128e894612034954006ef0e221641ddfcd3a43c/syntaxes/javascript.embedded.json#L45
https://github.com/ruschaaf/extended-embedded-languages/blob/c128e894612034954006ef0e221641ddfcd3a43c/syntaxes/javascript.embedded.json#L48

**Comment by ruschaaf** [comment]
I'm seeing those rules in https://github.com/microsoft/vscode/blob/main/extensions/javascript/syntaxes/JavaScript.tmLanguage.json, but yeah the rules aren't getting used. I'll remove them for now

**Comment by ruschaaf** [comment]
Just pushed a fix, will be in next release, thanks
