### ISSUE TITLE
Change file extension to official `.tmLanguage.json`

### ISSUE THREAD

**Issue by RedCMD** [ruschaaf/extended-embedded-languages#11]
Currently all the grammar files under `/syntaxes/` are `langId.embedded.json`

this should be changed to the more official JSON TextMate file name `langId.embedded.tmLanguage.json`

**Comment by ruschaaf** [comment]
Thanks for the suggestion! I'll rename the files for the next release

**Comment by ruschaaf** [comment]
Just pushed a fix, will be in next release, thanks
