### ISSUE TITLE
Can i use this extension for a my own language

### ISSUE THREAD

**Issue by IsmailCLN** [ruschaaf/extended-embedded-languages#12]
I have a simple programming language that I created for my precompiler. This language includes a code block syntax similar to the ```sql ``` syntax in markdown, which allows me to embed another language within it.

I assume that your extension is for popular languages. Is it possible for me to use your project for my own language as well?

**Comment by ruschaaf** [comment]
Thanks for your interest. Yeah this extension is really about adding new syntax highlighting rules to existing languages. If you are in control of the language yourself you don’t need this, but can include those embedded languages directly in your syntax highlighter. You could use the language files in this extension as a guide for how to do it.

**Comment by IsmailCLN** [comment]
Thank you, i'll do that.
