### ISSUE TITLE
Add "GitHub Actions Workflow" as an alias for YAML 

### ISSUE THREAD

**Issue by johnbillion** [ruschaaf/extended-embedded-languages#15]
Thanks for your work on this extension.

When editing a GitHub Actions workflow file and the GitHub Actions extension is installed, the language mode gets set to GitHub Actions Workflow instead of YAML. This means syntax highlighting doesn't work for embedded language strings even though the file is actually just a YAML file.

It would be great if this extension treated the GitHub Actions Workflow language mode the same as YAML language mode.

**Comment by ruschaaf** [comment]
Thanks, this will be in the next release

**Comment by azatoth** [comment]
> Thanks, this will be in the next release

I don't know if I missed an release but I don't see any releases since May last year; was this ticket accidentally closed?
