### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by DaRacci** [ruschaaf/extended-embedded-languages#16]
I've noticed that you arent too active on this repository, If you want to add myself as a maintainer I would be happy to help out.

**Comment by ruschaaf** [comment]
Hi! Appreciate your interest in this extension and your contributions. I'm planning on doing another release in a few weeks. So far it's been fairly quiet so I've been piling up several changes between releases but would definitely consider more active maintenance and support in the future. Thanks!
