### ISSUE TITLE
Intellisense and LSP support

### ISSUE THREAD

**Issue by DaRacci** [ruschaaf/extended-embedded-languages#6]
While I've made two PRs for new host languages I'm not too familier with vscode extensions, currently it seems that LSP and Intellisense doesn't work is there a way to possibly add support for it?

**Comment by ruschaaf** [comment]
Thanks for the contributions! I will take a look at those PRs shortly. I havent looked too deeply into LSP or intellisense. There is some documentation here (https://code.visualstudio.com/api/language-extensions/embedded-languages) with an example of “request forwarding” that sounds promising but that isn’t something I’ve tried out, and not sure how much the plugin would have to end up reimplementing the language parsers for that. On Apr 14, 2024, at 10:05 PM, Racci ***@***.***> wrote:﻿
While I've made two PRs for new host languages I'm not too familier with vscode extensions, currently it seems that LSP and Intellisense doesn't work is there a way to possibly add support for it?

**Comment by DaRacci** [comment]
That looks promising, I'll give it a look over when i get time.
