### ISSUE TITLE
Are you planning on Markdown support?

### ISSUE THREAD

**Issue by piscopancer** [ruschaaf/extended-embedded-languages#7]
Currently there is no appropriate markdown in js syntax highlighting solution, I searched all around the marketplace, failed to find one. 

I even issued about it on vscode's github [here](https://github.com/microsoft/vscode-textmate/issues/231#issuecomment-2108576223) and there was a person who gave me direction to your extension.

**Comment by piscopancer** [comment]
also that would be great if it was supported across all of `js`,`jsx`,`ts` and `tsx` formats and would work in severe cases like
```tsx
function Component() {
  return <Markdown>{/* md */`
# heading 1

- tomato
- orange
  `}</Markdown>
}
```

**Comment by ruschaaf** [comment]
Thanks for the suggestion! Markdown looks straightforward. Jsx and tsx would be good additions too, and it looks like their language definitions are mostly copies of typescript

**Comment by ruschaaf** [comment]
These should be in the next release

**Comment by kuanyui** [comment]
Waiting for the release of this feature for 5 months, is there any plan to release? Thanks.
