### ISSUE TITLE
Edge case when SQL comment followed by end of string

### ISSUE THREAD

**Issue by shane-tw** [ruschaaf/extended-embedded-languages#8]
Go example:
```go
query := test( /*sql*/ `
  -- hello world`)
```

The above should treat `-- hello world` as SQL.
Currently it is treating the `) as being part of the SQL comment.
This results in the highlighting being off for the rest of the file.

**Comment by ruschaaf** [comment]
I believe this is a limitation of the TextMate
Grammars that VSCode uses, where once an embedded language starts capturing content for part of a line there is no way for the host language to see it (ie the Go parser never sees the backtick so we don’t know that the code block is done). There is more info here: https://github.com/microsoft/vscode/issues/20488

**Comment by shane-tw** [comment]
Thanks for investigating. Closing in that case.
