### ISSUE TITLE
`"endCaptures"` in `Go` broken

### ISSUE THREAD

**Issue by RedCMD** [ruschaaf/extended-embedded-languages#9]
This is not how `"name"` inside `"endCaptures"` works
![image](https://github.com/ruschaaf/extended-embedded-languages/assets/33529441/603591ea-5e4e-4372-b12b-d96ffe77c6c5)

you need to target a capture group
![image](https://github.com/ruschaaf/extended-embedded-languages/assets/33529441/882ff6f8-d77a-4647-8766-5ae967f5f12f)

https://github.com/ruschaaf/extended-embedded-languages/blob/c128e894612034954006ef0e221641ddfcd3a43c/syntaxes/go.embedded.json#L39-L41

**Comment by ruschaaf** [comment]
Just pushed a fix, will be in next release, thanks
